name: update_service
description: Utility service that check whether an update is available in PlayStore or AppStore
version: 1.0.1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  html: ">=0.15.1 <0.16.0"
  http: ">=0.13.5 <0.14.0"
  package_info_plus: ">=3.0.0 <4.0.0"
  url_launcher: ">=6.1.6 <7.0.0"

dev_dependencies:
  lints: ">=2.0.1 <3.0.0"
  test: ">=1.21.0 <2.0.0"
