name: update_service
description: Utility service that check whether an update is available in PlayStore or AppStore
version: 1.0.1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  http: ^0.13.4
  package_info_plus: ^1.4.2
  url_launcher: ^6.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.3
