name: update_service
description: Utility service that check whether an update is available in PlayStore or AppStore
version: 1.3.1
homepage: https://github.com/XperiTech
repository: https://github.com/XperiTech/flutter_tools


environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ">=2.4.0 <3.0.0"
  html: ">=0.15.1 <0.16.0"
  http: ">=1.0.0 <2.0.0"
  package_info_plus: ">=4.0.0 <9.0.0"
  url_launcher: ">=6.1.6 <7.0.0"

dev_dependencies:
  build_runner: ">=2.4.0 <3.0.0"
  freezed: ">=2.4.0 <3.0.0"
  lints: ">=2.0.1 <3.0.0"
  test: ">=1.24.0 <2.0.0"
